/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.datacoper.locacaoequipamentos.client.cliente;

import com.datacoper.locacaoequipamentos.common.exception.BusinessException;
import com.datacoper.locacaoequipamentos.common.model.Cliente;
import com.datacoper.locacaoequipamentos.common.model.Endereco;
import com.datacoper.locacaoequipamentos.common.service.ClienteService;
import com.datacoper.locacaoequipamentos.common.service.ServiceLocator;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Java
 */
public class CadastroCliente extends javax.swing.JInternalFrame {

	/**
	 * Creates new form CadastroCliente
	 */
	SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
	Date date = new Date(System.currentTimeMillis());
	static Boolean ExcluiCliente = false;
	static Cliente cliente;
	private static String operacao = null;
	private ClienteService clienteService;

	public CadastroCliente() {
		initComponents();
		clienteService = getClienteService();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel5 = new javax.swing.JLabel();
		iDClienteField = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		dataCadastroClienteField = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		cpfClienteField = new javax.swing.JTextField();
		try {
			javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter(
					"###.###.###-##");
			cpfClienteField = new javax.swing.JFormattedTextField(cpf);
		} catch (Exception e) {
		}
		jLabel1 = new javax.swing.JLabel();
		nomeClienteField = new javax.swing.JTextField();
		rgClienteField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		estadoCivilClienteField = new javax.swing.JComboBox();
		jLabel11 = new javax.swing.JLabel();
		emailClienteField = new javax.swing.JTextField();
		sexoClienteField = new javax.swing.JComboBox();
		jLabel10 = new javax.swing.JLabel();
		telefoneClienteField = new javax.swing.JTextField();
		try {
			javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter(
					"(##)####-####");
			telefoneClienteField = new javax.swing.JFormattedTextField(cpf);
		} catch (Exception e) {
		}
		nascimentoClienteField = new com.toedter.calendar.JDateChooser();
		jPanel3 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		cepClienteField = new javax.swing.JTextField();
		try {
			javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter(
					"#####-###");
			cepClienteField = new javax.swing.JFormattedTextField(cpf);
		} catch (Exception e) {
		}
		jLabel14 = new javax.swing.JLabel();
		numeroClienteField = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		ruaClienteField = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		cidadeClienteField = new javax.swing.JTextField();
		complementeClienteField = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		estadoClienteField = new javax.swing.JComboBox();
		jLabel28 = new javax.swing.JLabel();
		bairroClienteField = new javax.swing.JTextField();
		excluirButton = new javax.swing.JButton();
		editarButton = new javax.swing.JButton();
		adicionarButton = new javax.swing.JButton();

		jLabel5.setText("Código:");

		iDClienteField.setEditable(false);
		iDClienteField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				iDClienteFieldActionPerformed(evt);
			}
		});

		jLabel7.setText("Data do Cadastro:");

		dataCadastroClienteField.setEditable(false);
		dataCadastroClienteField
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						dataCadastroClienteFieldActionPerformed(evt);
					}
				});

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Pessoa"));
		jPanel2.setMaximumSize(new java.awt.Dimension(1073, 468));
		jPanel2.setMinimumSize(new java.awt.Dimension(1073, 468));

		jLabel3.setText("* RG:");

		jLabel2.setText("* CPF:");

		cpfClienteField
				.setToolTipText("Insira o CPF do Cliente. *(Obrigatório)");
		cpfClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));
		cpfClienteField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cpfClienteFieldActionPerformed(evt);
			}
		});

		jLabel1.setText("* Nome:");

		nomeClienteField
				.setToolTipText("Insira o nome completo do Cliente. *(Obrigatório)");
		nomeClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		rgClienteField
				.setToolTipText("Insira o RG do Cliente, somente números. *(Obrigatório)");
		rgClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel4.setText("Sexo:");

		jLabel8.setText("* Data de Nascimento:");

		jLabel9.setText("Estado Civil:");

		estadoCivilClienteField.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Casado", "Solteiro", "Viúvo" }));
		estadoCivilClienteField.setSelectedIndex(1);
		estadoCivilClienteField
				.setToolTipText("Informe o estado civil do Cliente.");
		estadoCivilClienteField
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						estadoCivilClienteFieldActionPerformed(evt);
					}
				});

		jLabel11.setText("E-mail:");

		emailClienteField.setToolTipText("Insira o e-mail do Cliente.");
		emailClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		sexoClienteField.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Masculino", "Feminino" }));
		sexoClienteField.setToolTipText("Informe qual o sexo do Cliente.");

		jLabel10.setText("* Telefone:");

		telefoneClienteField
				.setToolTipText("Insira o número do telefone do Cliente. *(Obrigatório)");
		telefoneClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												22,
																												Short.MAX_VALUE)
																										.addComponent(
																												rgClienteField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												265,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																jLabel1))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																nomeClienteField,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																265,
																																Short.MAX_VALUE)
																														.addComponent(
																																cpfClienteField))))
																		.addGap(18,
																				18,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jLabel11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								47,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												sexoClienteField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jLabel9)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												estadoCivilClienteField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												123,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								telefoneClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								126,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								emailClienteField))
																		.addGap(390,
																				390,
																				390))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				nascimentoClienteField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(11, 11, 11)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				telefoneClienteField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				20,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(32,
																				32,
																				32)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								sexoClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								estadoCivilClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								nomeClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel10))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																cpfClienteField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																20,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel3)
																														.addComponent(
																																rgClienteField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																20,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel11)
																														.addComponent(
																																emailClienteField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																20,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel4)))))
										.addGap(12, 12, 12)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel8)
														.addComponent(
																nascimentoClienteField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Endereço"));

		jLabel12.setText("* Rua:");

		cepClienteField
				.setToolTipText("Insira o CEP de residência do Cliente.");
		cepClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel14.setText("* Número:");

		numeroClienteField
				.setToolTipText("Insira o número da residência do Cliente. *(Obrigatório)");
		numeroClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel13.setText("CEP:");

		ruaClienteField
				.setToolTipText("Insira o nome da rua de residência do Cliente. *(Obrigatório)");
		ruaClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel15.setText("* Cidade:");

		cidadeClienteField
				.setToolTipText("Insira a cidade de residência do Cliente. *(Obrigatório)");
		cidadeClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		complementeClienteField
				.setToolTipText("Insira o complemento da residência do Cliente.");
		complementeClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel16.setText("Complemento: ");

		jLabel17.setText("Estado:");

		estadoClienteField.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES",
						"GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE",
						"PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE",
						"TO" }));
		estadoClienteField.setSelectedIndex(15);
		estadoClienteField
				.setToolTipText("Informe o estado de residência do Cliente.");

		jLabel28.setText("* Bairro:");

		bairroClienteField
				.setToolTipText("Insira o bairro de residência do Cliente. *(Obrigatório)");
		bairroClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(
																				jPanel3Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel15)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								cidadeClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								264,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jPanel3Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel12)
																						.addGap(24,
																								24,
																								24)
																						.addComponent(
																								ruaClienteField)))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel28)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				bairroClienteField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				264,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(
																				jLabel16,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel17,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				72,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jLabel13))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				cepClienteField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				101,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel14)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				numeroClienteField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																complementeClienteField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																261,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																estadoClienteField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																106,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel17)
																						.addComponent(
																								estadoClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel16)
																						.addComponent(
																								complementeClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel15)
																						.addComponent(
																								cidadeClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								ruaClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel12))))
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(6,
																				6,
																				6)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel13)
																						.addComponent(
																								numeroClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel28)
																						.addComponent(
																								bairroClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								cepClienteField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								20,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel14))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		excluirButton.setText("Excluir");
		excluirButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				excluirButtonActionPerformed(evt);
			}
		});

		editarButton.setText("Editar");
		editarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editarButtonActionPerformed(evt);
			}
		});

		adicionarButton.setText("Adicionar");
		adicionarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adicionarButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(excluirButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										100,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(editarButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										100,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(adicionarButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										100,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(35, 35, 35))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(10, 10, 10)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(35, Short.MAX_VALUE))
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(10,
																						10,
																						10)
																				.addComponent(
																						jLabel5)
																				.addGap(18,
																						18,
																						18)
																				.addComponent(
																						iDClienteField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						55,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(18,
																						18,
																						18)
																				.addComponent(
																						jLabel7)
																				.addGap(18,
																						18,
																						18)
																				.addComponent(
																						dataCadastroClienteField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						83,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(
																		jPanel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		713,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(35, 35, 35))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(209, 209, 209)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(excluirButton)
												.addComponent(editarButton)
												.addComponent(adicionarButton))
								.addGap(126, 126, 126))
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel5)
																.addComponent(
																		iDClienteField,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jLabel7)
																.addComponent(
																		dataCadastroClienteField,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(
														jPanel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														144,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(301,
														Short.MAX_VALUE))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void iDClienteFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_iDClienteFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_iDClienteFieldActionPerformed

	private void dataCadastroClienteFieldActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dataCadastroClienteFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_dataCadastroClienteFieldActionPerformed

	private void estadoCivilClienteFieldActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoCivilClienteFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_estadoCivilClienteFieldActionPerformed

	private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adicionarButtonActionPerformed
		String cpf, telefone, nome, rg, sexo, estadoCivil, dataCadastro, dataNascimento, email = null;
		String cidade, rua, bairro, estado, cep, complemento = null;
		int numero, id = 0;
		Cliente c = new Cliente();
		Date data = new Date();
		data = nascimentoClienteField.getDate();
		if (nascimentoClienteField.getDate() == null) {
			cpfClienteField.setBorder(javax.swing.BorderFactory
					.createLineBorder(new java.awt.Color(153, 153, 153)));
			JOptionPane
					.showMessageDialog(
							null,
							"Por favor, preencha o campo Data de Nascimento de forma correta",
							"Erro", JOptionPane.ERROR_MESSAGE);
			return;
		} else if (numeroClienteField.getText().equals("")) {
			numeroClienteField.setBorder(javax.swing.BorderFactory
					.createLineBorder(new java.awt.Color(153, 153, 153)));
			JOptionPane.showMessageDialog(null,
					"Por favor, preencha o campo número crretamente.", "Erro",
					JOptionPane.ERROR_MESSAGE);
			return;
		} else {
			// if(!nomeClienteField.getText().isEmpty() ||
			// !cpfClienteField.getText().isEmpty())
			if (!iDClienteField.getText().isEmpty())
				id = Integer.valueOf(iDClienteField.getText());
			dataNascimento = formatarDate.format(data);
			cpf = cpfClienteField.getText();
			telefone = telefoneClienteField.getText();
			nome = nomeClienteField.getText();
			rg = rgClienteField.getText();
			email = emailClienteField.getText();
			sexo = (String) sexoClienteField.getSelectedItem();
			estadoCivil = (String) estadoCivilClienteField.getSelectedItem();
			dataCadastro = formatarDate.format(date);
			cidade = cidadeClienteField.getText();
			rua = ruaClienteField.getText();
			complemento = complementeClienteField.getText();
			numero = Integer.parseInt(numeroClienteField.getText());
			estado = (String) estadoClienteField.getSelectedItem();
			bairro = bairroClienteField.getText();
			cep = cepClienteField.getText();
			//

			c.setNome(nome);
			c.setCpf(cpf);
			c.setRg(rg);
			c.setDataCadastro(dataCadastro);
			c.setEstadoCivil(estadoCivil);
			c.setSexo(sexo);
			c.setEmail(email);
			c.setTelefone(telefone);
			c.setDataNascimento(dataNascimento);
			Endereco end = new Endereco();
			end.setEstado(estado);
			end.setCidade(cidade);
			end.setRua(rua);
			end.setBairro(bairro);
			end.setCep(cep);
			end.setNumero(numero);
			end.setComplemento(complemento);
			c.setEndereco(end);
		}

		if (adicionarButton.getText().equals("Adicionar")) {

			try {
				this.clienteService.gravar(c);
				JOptionPane.showMessageDialog(null,
						"Cliente cadastrado com sucesso!", "Cadastro",
						JOptionPane.INFORMATION_MESSAGE);
				atualizaCampos();
			} catch (BusinessException ex) {
				JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro",
						JOptionPane.ERROR_MESSAGE);
			}

			// if (gravado) { //Cadastra o Cliente
			//
			// ExcluiCliente = false;
			// } else {
			// JOptionPane.showMessageDialog(null,
			// "Não foi possivel cadastrar este Cliente", "Erro",
			// JOptionPane.ERROR_MESSAGE);
			// }

		} else if (adicionarButton.getText().equals("Editar Cliente")) {
			c.setIdCliente(id);
			boolean gravado = false;
			try {
				// gravado = this.clienteService.updateCliente(c);
			} catch (Exception ex) {
				Logger.getLogger(CadastroCliente.class.getName()).log(
						Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro",
						JOptionPane.ERROR_MESSAGE);
			}

			if (gravado) // Cadastra o Cliente
			{
				JOptionPane.showMessageDialog(null,
						"Cliente Editado com sucesso!", "Cadastro",
						JOptionPane.INFORMATION_MESSAGE);
				atualizaCampos();
				ExcluiCliente = false;
			} else {
				JOptionPane.showMessageDialog(null,
						"Não foi possivel editar este Cliente", "Erro",
						JOptionPane.ERROR_MESSAGE);
			}

		} else if (adicionarButton.getText().equals("Excluir Cliente")) {
			c.setIdCliente(id);
			boolean gravado = false;
			try {
				// gravado = this.clienteService.excluir(c);
			} catch (Exception ex) {
				Logger.getLogger(CadastroCliente.class.getName()).log(
						Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro",
						JOptionPane.ERROR_MESSAGE);

			}

			if (gravado) // Cadastra o Cliente
			{
				JOptionPane.showMessageDialog(null,
						"Cliente excluído com sucesso!", "Cadastro",
						JOptionPane.INFORMATION_MESSAGE);
				atualizaCampos();
				ExcluiCliente = false;
			} else {
				JOptionPane.showMessageDialog(null,
						"Não foi possivel excluir este Cliente", "Erro",
						JOptionPane.ERROR_MESSAGE);
			}

		}
	}// GEN-LAST:event_adicionarButtonActionPerformed

	private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarButtonActionPerformed
		if (!editarButton.getText().equals("Cancelar")) {
			BuscaCliente b = new BuscaCliente("editacliente", this);
			b.setVisible(true);
			adicionarButton.setText("Editar Cliente");
			editarButton.setText("Cancelar");
			excluirButton.setVisible(false);
		} else {
			atualizaCampos();
		}
	}// GEN-LAST:event_editarButtonActionPerformed

	private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirButtonActionPerformed
		if (!excluirButton.getText().equals("Cancelar")) {
			BuscaCliente b = new BuscaCliente("editacliente", this);
			b.setVisible(true);
			adicionarButton.setText("Excluir Cliente");
			editarButton.setText("Cancelar");
			excluirButton.setVisible(false);
		} else {
			atualizaCampos();
		}
	}// GEN-LAST:event_excluirButtonActionPerformed

	private void cpfClienteFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cpfClienteFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cpfClienteFieldActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton adicionarButton;
	private static javax.swing.JTextField bairroClienteField;
	private static javax.swing.JTextField cepClienteField;
	private static javax.swing.JTextField cidadeClienteField;
	private static javax.swing.JTextField complementeClienteField;
	private static javax.swing.JTextField cpfClienteField;
	private static javax.swing.JTextField dataCadastroClienteField;
	private javax.swing.JButton editarButton;
	private static javax.swing.JTextField emailClienteField;
	private static javax.swing.JComboBox estadoCivilClienteField;
	private static javax.swing.JComboBox estadoClienteField;
	private javax.swing.JButton excluirButton;
	private static javax.swing.JTextField iDClienteField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private static com.toedter.calendar.JDateChooser nascimentoClienteField;
	private static javax.swing.JTextField nomeClienteField;
	private static javax.swing.JTextField numeroClienteField;
	private static javax.swing.JTextField rgClienteField;
	private static javax.swing.JTextField ruaClienteField;
	private static javax.swing.JComboBox sexoClienteField;
	private static javax.swing.JTextField telefoneClienteField;

	// End of variables declaration//GEN-END:variables

	public void atualizaCampos() {
		nascimentoClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));
		telefoneClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));
		cpfClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));
		cepClienteField.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));
		iDClienteField.setText(""); // Depois criar metodo para pegar o prox id
									// a ser cadastrado
		cpfClienteField.setText("");
		telefoneClienteField.setText("");
		nomeClienteField.setText("");
		rgClienteField.setText("");
		emailClienteField.setText("");
		dataCadastroClienteField.setText("");
		cidadeClienteField.setText("");
		cepClienteField.setText("");
		ruaClienteField.setText("");
		complementeClienteField.setText("");
		numeroClienteField.setText("");
		bairroClienteField.setText("");
		dataCadastroClienteField.setText(formatarDate.format(date));
		sexoClienteField.setSelectedIndex(0);
		estadoCivilClienteField.setSelectedIndex(1);
		estadoClienteField.setSelectedIndex(15);
		adicionarButton.setText("Adicionar");
		editarButton.setVisible(true);
		excluirButton.setVisible(true);
		editarButton.setText("Editar");
		excluirButton.setText("Excluir");
		bairroClienteField.setText("");

	}

	public static void setCliente(Cliente c) {
		CadastroCliente.cliente = c;
		addCliente();
	}

	private static void addCliente() {
		iDClienteField.setText(String.valueOf(cliente.getIdCliente())); // Depois
																		// criar
																		// metodo
																		// para
																		// pegar
																		// o
																		// prox
																		// id a
																		// ser
																		// cadastrado
		cpfClienteField.setText(cliente.getCpf());
		telefoneClienteField.setText(cliente.getTelefone());
		nomeClienteField.setText(cliente.getNome());
		rgClienteField.setText(cliente.getRg());
		emailClienteField.setText(cliente.getEmail());
		dataCadastroClienteField.setText(cliente.getDataCadastro());
		cidadeClienteField.setText(cliente.getEndereco().getCidade());
		cepClienteField.setText(cliente.getEndereco().getCep());
		ruaClienteField.setText(cliente.getEndereco().getRua());
		complementeClienteField.setText(cliente.getEndereco().getComplemento());
		numeroClienteField.setText(String.valueOf(cliente.getEndereco()
				.getNumero()));
		bairroClienteField.setText(cliente.getEndereco().getBairro());

		String formato = "dd/MM/yyyy";
		Date DataTemp = new Date();
		try {
			DataTemp = new SimpleDateFormat(formato).parse(cliente
					.getDataNascimento());
		} catch (ParseException ex) {
			Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE,
					null, ex);
		}
		nascimentoClienteField.setDate(DataTemp);

		sexoClienteField.setSelectedItem(cliente.getSexo());
		estadoCivilClienteField.setSelectedItem(cliente.getEstadoCivil());
		estadoClienteField.setSelectedItem(cliente.getEndereco().getEstado());

	}

	public ClienteService getClienteService() {
		if (clienteService == null) {
			clienteService = new ServiceLocator()
					.loadService(ClienteService.class);
			System.out.println("ClienteService: " + clienteService);
		}
		return clienteService;
	}

	public void setClienteService(ClienteService clienteService) {
		clienteService = clienteService;
	}
}
